webtalk_init -webtalk_dir D:/Xilinx/Vivado/2020.1_Projects/Ring_Oscillator/Ring_Oscillator.sim/sim_1/synth/timing/xsim/xsim.dir/tb_ring_osc_top_time_synth/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Apr 27 17:58:37 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "200973130_1777501258_210717535_647" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "6c0e21c0-8814-43bc-be44-12e73c285f9c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "89f8cb9552144acabdd05e2a31ca0b4c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "56" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 1700 Eight-Core Processor          " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2994 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "502 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7736_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4210603978 -regid "200973130_1777501258_210717535_647" -xml D:/Xilinx/Vivado/2020.1_Projects/Ring_Oscillator/Ring_Oscillator.sim/sim_1/synth/timing/xsim/xsim.dir/tb_ring_osc_top_time_synth/webtalk/usage_statistics_ext_xsim.xml -html D:/Xilinx/Vivado/2020.1_Projects/Ring_Oscillator/Ring_Oscillator.sim/sim_1/synth/timing/xsim/xsim.dir/tb_ring_osc_top_time_synth/webtalk/usage_statistics_ext_xsim.html -wdm D:/Xilinx/Vivado/2020.1_Projects/Ring_Oscillator/Ring_Oscillator.sim/sim_1/synth/timing/xsim/xsim.dir/tb_ring_osc_top_time_synth/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
