# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/School/HW_security/fpga-power-side-channel-attack/Ring_Oscillator/Ring_Oscillator.srcs/constrs_1/new/Ring_Osc.xdc

# Block Designs: bd/single_power_virus/single_power_virus.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==single_power_virus || ORIG_REF_NAME==single_power_virus} -quiet] -quiet

# IP: bd/single_power_virus/ip/single_power_virus_power_virus_0_1/single_power_virus_power_virus_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==single_power_virus_power_virus_0_1 || ORIG_REF_NAME==single_power_virus_power_virus_0_1} -quiet] -quiet

# IP: bd/single_power_virus/ip/single_power_virus_vio_0_1/single_power_virus_vio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==single_power_virus_vio_0_1 || ORIG_REF_NAME==single_power_virus_vio_0_1} -quiet] -quiet

# IP: bd/single_power_virus/ip/single_power_virus_clk_wiz_1/single_power_virus_clk_wiz_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==single_power_virus_clk_wiz_1 || ORIG_REF_NAME==single_power_virus_clk_wiz_1} -quiet] -quiet

# XDC: bd/single_power_virus/single_power_virus_ooc.xdc
