# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/School/HW_security/fpga-power-side-channel-attack/Power_Virus_Test/Power_Virus_Test.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_3/design_1_clk_wiz_3.xci
# IP: The module: 'design_1_clk_wiz_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/School/HW_security/fpga-power-side-channel-attack/Power_Virus_Test/Power_Virus_Test.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_3/design_1_clk_wiz_3_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_clk_wiz_3'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/School/HW_security/fpga-power-side-channel-attack/Power_Virus_Test/Power_Virus_Test.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_3/design_1_clk_wiz_3.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_clk_wiz_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/School/HW_security/fpga-power-side-channel-attack/Power_Virus_Test/Power_Virus_Test.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_3/design_1_clk_wiz_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_clk_wiz_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/School/HW_security/fpga-power-side-channel-attack/Power_Virus_Test/Power_Virus_Test.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_3/design_1_clk_wiz_3.xci
# IP: The module: 'design_1_clk_wiz_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/School/HW_security/fpga-power-side-channel-attack/Power_Virus_Test/Power_Virus_Test.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_3/design_1_clk_wiz_3_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_clk_wiz_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/School/HW_security/fpga-power-side-channel-attack/Power_Virus_Test/Power_Virus_Test.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_3/design_1_clk_wiz_3.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_clk_wiz_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/School/HW_security/fpga-power-side-channel-attack/Power_Virus_Test/Power_Virus_Test.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_3/design_1_clk_wiz_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_clk_wiz_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
