# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/School/HW_security/fpga-power-side-channel-attack/Power_Virus_Test/Power_Virus_Test.srcs/sources_1/bd/single_power_virus/ip/single_power_virus_clk_wiz_1/single_power_virus_clk_wiz_1.xci
# IP: The module: 'single_power_virus_clk_wiz_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/School/HW_security/fpga-power-side-channel-attack/Power_Virus_Test/Power_Virus_Test.srcs/sources_1/bd/single_power_virus/ip/single_power_virus_clk_wiz_1/single_power_virus_clk_wiz_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'single_power_virus_clk_wiz_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/School/HW_security/fpga-power-side-channel-attack/Power_Virus_Test/Power_Virus_Test.srcs/sources_1/bd/single_power_virus/ip/single_power_virus_clk_wiz_1/single_power_virus_clk_wiz_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'single_power_virus_clk_wiz_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/School/HW_security/fpga-power-side-channel-attack/Power_Virus_Test/Power_Virus_Test.srcs/sources_1/bd/single_power_virus/ip/single_power_virus_clk_wiz_1/single_power_virus_clk_wiz_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'single_power_virus_clk_wiz_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/School/HW_security/fpga-power-side-channel-attack/Power_Virus_Test/Power_Virus_Test.srcs/sources_1/bd/single_power_virus/ip/single_power_virus_clk_wiz_1/single_power_virus_clk_wiz_1.xci
# IP: The module: 'single_power_virus_clk_wiz_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/School/HW_security/fpga-power-side-channel-attack/Power_Virus_Test/Power_Virus_Test.srcs/sources_1/bd/single_power_virus/ip/single_power_virus_clk_wiz_1/single_power_virus_clk_wiz_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'single_power_virus_clk_wiz_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/School/HW_security/fpga-power-side-channel-attack/Power_Virus_Test/Power_Virus_Test.srcs/sources_1/bd/single_power_virus/ip/single_power_virus_clk_wiz_1/single_power_virus_clk_wiz_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'single_power_virus_clk_wiz_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/School/HW_security/fpga-power-side-channel-attack/Power_Virus_Test/Power_Virus_Test.srcs/sources_1/bd/single_power_virus/ip/single_power_virus_clk_wiz_1/single_power_virus_clk_wiz_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'single_power_virus_clk_wiz_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
