# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/Xilinx/Vivado/2020.1_Projects/Tutorials/blinky/blinky.srcs/constrs_1/new/LED_ILA_test.xdc

# XDC: new/Ring_Osc.xdc

# Block Designs: bd/design_2/design_2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2 || ORIG_REF_NAME==design_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_ila_0_0/design_2_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_ila_0_0 || ORIG_REF_NAME==design_2_ila_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_vio_0_0/design_2_vio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_vio_0_0 || ORIG_REF_NAME==design_2_vio_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_c_counter_binary_0_0/design_2_c_counter_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_c_counter_binary_0_0 || ORIG_REF_NAME==design_2_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xlslice_0_0/design_2_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_xlslice_0_0 || ORIG_REF_NAME==design_2_xlslice_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_util_vector_logic_0_0/design_2_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_util_vector_logic_0_0 || ORIG_REF_NAME==design_2_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_clk_wiz_1_0/design_2_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_clk_wiz_1_0 || ORIG_REF_NAME==design_2_clk_wiz_1_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_ring_osc_top_0_1/design_2_ring_osc_top_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_ring_osc_top_0_1 || ORIG_REF_NAME==design_2_ring_osc_top_0_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_util_vector_logic_1_0/design_2_util_vector_logic_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_util_vector_logic_1_0 || ORIG_REF_NAME==design_2_util_vector_logic_1_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_power_virus_bank_0_0/design_2_power_virus_bank_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_power_virus_bank_0_0 || ORIG_REF_NAME==design_2_power_virus_bank_0_0} -quiet] -quiet

# XDC: bd/design_2/design_2_ooc.xdc
