set_property SRC_FILE_INFO {cfile:d:/School/HW_security/fpga-power-side-channel-attack/Power_Virus_Test/Power_Virus_Test.srcs/sources_1/bd/single_power_virus/ip/single_power_virus_clk_wiz_1/single_power_virus_clk_wiz_1/single_power_virus_clk_wiz_1_in_context.xdc rfile:../../../Power_Virus_Test.srcs/sources_1/bd/single_power_virus/ip/single_power_virus_clk_wiz_1/single_power_virus_clk_wiz_1/single_power_virus_clk_wiz_1_in_context.xdc id:1 order:EARLY scoped_inst:single_power_virus_i/clk_wiz} [current_design]
set_property SRC_FILE_INFO {cfile:D:/School/HW_security/fpga-power-side-channel-attack/Ring_Oscillator/Ring_Oscillator.srcs/constrs_1/new/Ring_Osc.xdc rfile:../../../../Ring_Oscillator/Ring_Oscillator.srcs/constrs_1/new/Ring_Osc.xdc id:2} [current_design]
current_instance single_power_virus_i/clk_wiz
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 8.000 [get_ports -no_traverse {}]
set_property src_info {type:SCOPED_XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -source [get_ports clk_in1] -edges {1 2 3} -edge_shift {0.000 1.000 2.000} [get_ports {}]
current_instance
set_property src_info {type:XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K18 [get_ports reset_rtl]
set_property src_info {type:XDC file:2 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:6 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets clk]
set_property src_info {type:XDC file:2 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets design_2_i/ring_osc_top_0/inst/ROs[*].RO_i/osc_1/osc_out]
